version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:586794446862:task-definition/task-meusite:1"
        LoadBalancerInfo:
          ContainerName: "meusite-container"
          ContainerPort: 80

