version: 0.0
os: linux
files:
  - source: ./
    destination: /app

hooks:
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 180
      runas: root
