version: 0.2
env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "586794446862"
    REPOSITORY_NAME: "meusite"
    IMAGE_TAG: "$(git rev-parse --short HEAD)"  # Usando o hash do commit como tag única

phases:
  install:
    commands:
      - echo "Instalando dependências e ferramentas..."
      - aws --version
      - echo "Instalando Docker..."
      - yum install docker -y
      - echo "Iniciando o Docker..."
      - nohup dockerd &  # Inicia o Docker em segundo plano

  pre_build:
    commands:
      - echo "Login no ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME
      - echo "Restaurando dependências do projeto .NET..."
      - ~/.dotnet/dotnet restore

  build:
    commands:
      - echo "Compilando e publicando o aplicativo .NET..."
      - ~/.dotnet/dotnet publish -c Release -o out
      - echo "Construindo a imagem Docker com tag $IMAGE_TAG..."
      - docker build -t $REPOSITORY_NAME:$IMAGE_TAG .  # Usando a tag única do commit
      - docker tag $REPOSITORY_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Gerando o arquivo imagedefinitions.json..."
      - printf '[{"name":"meusite", "imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s" } ]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
      - echo "Subindo a imagem para o ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG  # Push da imagem com a tag única

artifacts:
  files:
    - imagedefinitions.json
